name: Logless Release

on:
  push:
    tags:
      - v*

env:
  LIB_NAME: Logless

jobs:
  build-and-release:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.102
        
    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: Build Library
      run: dotnet build --configuration Release
      
    - name: Zip Artifact
      run: zip -rjD ${{ env.LIB_NAME }}_${{ github.ref_name }}.zip ${{ github.workspace }}/bin/Release/**/${{ env.LIB_NAME }}.dll
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.LIB_NAME }} ${{ github.ref_name }}
        artifacts: ${{ env.LIB_NAME }}_${{ github.ref_name }}.zip
        body: |
          Release of ${{ env.LIB_NAME }} ${{ github.ref_name }}
        generateReleaseNotes: true
        makeLatest: true
